---
title: "Starbucks"
author: "Matthew"
date: "12/22/2021"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
theme_set(theme_bw())
starbucks <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-12-21/starbucks.csv')

glimpse(starbucks)
starbucks %>%
  count(milk, sort = TRUE) # count different columns

starbucks$milk <- as.factor(starbucks$milk) # change to factor with levels
levels(starbucks$milk) <- list("none" = 0, "nonfat" = 1, "2%" = 2,
                               "soy" = 3, "coconut" = 4, "whole" = 5)
starbucks %>%
  count(trans_fat_g)
starbucks$trans_fat_g[starbucks$trans_fat_g == "02"] <- "0.2"

starbucks <- starbucks %>%
  mutate(trans_fat_g = as.numeric(trans_fat_g),
         fiber_g = as.numeric(fiber_g))

```

# Calories
```{r}

starbucks %>%
  ggplot(aes(whip, calories, group = whip)) + geom_boxplot()
wo_whip <- starbucks %>%
  filter(whip == 0) # without whip
summary(aov(calories ~ milk, wo_whip))

```


```{r}

# Calories by milk, facet by whip
starbucks %>%
  ggplot(aes(milk, calories)) + geom_boxplot() + facet_wrap(~whip)

```


```{r}

# with milk only plot
starbucks %>%
  filter(milk != "none") %>%
  ggplot(aes(milk, calories)) + geom_boxplot() + facet_wrap(~whip)

```

```{r}

# with milk aov
w_milk <- starbucks %>%
  filter(milk != "none")

summary(aov(calories ~ milk, w_milk))

starbucks %>%
  count(milk)

```

```{r}

# df for attempting pairs of t.tests
quickt <- starbucks %>%
  filter(milk == "nonfat" | milk == "2%")
t.test(calories ~ milk, quickt)

# Pairwise t.test 
pairwise.t.test(starbucks$calories, starbucks$milk, p.adjust.method = "none",
                pool.sd = FALSE)

starbucks %>%
  ggplot(aes(size, calories)) + geom_boxplot()

```

```{r}

# top 15 median calorie drinks
starbucks %>%
  group_by(product_name) %>%
  summarize(n = median(calories)) %>%
  arrange(-n) %>%
  head(15) %>%
  ggplot(aes(n, fct_reorder(product_name, n))) + geom_col() + labs(y = "name")

```

## Carbs and Fat
```{r}

# Comparing fat and carbs, relating to calories
starbucks %>%
  select(calories, total_fat_g, total_carbs_g) %>%
  gather(-calories, key = "nutrient", value = "value") %>%
  ggplot(aes(x = value, y = calories, alpha = 0.2)) + geom_jitter() + 
  facet_wrap(~nutrient) + geom_smooth(method = "lm")

# Linear model with fat and carbs
summary(lm(calories ~ total_fat_g + total_carbs_g, starbucks)) # correctly predicts calories with Coef(4(carbs) and 10(fat)), which is close to empirical values
```

# Caffeine
```{r}

# caffeine and calories
starbucks_fct <- starbucks %>%
  select(caffeine_mg, calories) %>%
  mutate(caffeine_mg = as.factor(caffeine_mg)) # Caffeine to factor
starbucks_fct %>%
  ggplot(aes(fct_lump(caffeine_mg, 12), calories)) + geom_boxplot() + labs(x = "caffeine")

# Caffeine and serving size
starbucks %>%
  ggplot(aes(serv_size_m_l, caffeine_mg, group = serv_size_m_l)) + geom_boxplot()

starbucks %>%
  filter(serv_size_m_l == 0) %>%
  count(product_name, sort = TRUE)

```

# Carbs, Fiber and Sugar
```{r}

# Lm total carbs by sugar and fiber
summary(lm(total_carbs_g ~ fiber_g + sugar_g, starbucks))

# Total carbs by sugar, colored by fiber
starbucks %>%
  ggplot(aes(sugar_g, total_carbs_g, color = fiber_g)) + geom_point()

# Average sugar and fiber per drink
starbucks %>%
  summarize(sugar = mean(sugar_g),
            fiber = mean(fiber_g))

# Checking if fiber + sugar = total carbs
starbucks %>%
  select(total_carbs_g, fiber_g, sugar_g) %>%
  mutate(diff = total_carbs_g - fiber_g - sugar_g) %>%
  summarize(mdiff = mean(diff))
```

# Serving size and mL
```{r}
# Checking size and serv_size
starbucks %>%
  group_by(serv_size_m_l, size) %>%
  count() %>%
  arrange(size)

# Checking venti having two different size_ml
starbucks %>%
  filter(size == "venti") %>%
  group_by(serv_size_m_l) %>%
  count(product_name, sort = TRUE)

# New (Iced/Frapp = Cold) column
temp_star <- starbucks %>%
  filter(size == "venti") %>%
  mutate(temp = as.factor(
    ifelse(str_detect(product_name,
                      'Iced|Frappuccino|Cold|ice|Refreshers|Lemonade'),
           "Cold", "Hot")))

# Venti mL compared with temp
temp_star %>%
  ggplot(aes(temp, serv_size_m_l, color = temp)) + geom_jitter() + labs(y = "Serving Size (mL)")

# Chisq
chisq.test(table(temp_star$temp, temp_star$serv_size_m_l))

# Plot counting the 2 different mL sizes by Hot/Cold drinks
temp_star %>%
  group_by(temp, serv_size_m_l) %>%
  ggplot(aes(as.factor(serv_size_m_l), fill = temp)) + 
  geom_bar(position = position_dodge(preserve = 'single')) + labs(y = "count", x = "Size (mL)") +
  scale_fill_hue(direction = -1)

# Checking specifics from plot
temp_star %>%
  filter(temp == "Cold" & serv_size_m_l == 591) %>%
  count(product_name)

# Calories by size mL for Venti
temp_star %>%
  group_by(serv_size_m_l) %>%
  ggplot(aes(serv_size_m_l, calories, group = serv_size_m_l)) + 
  geom_boxplot() + geom_jitter(width = 10, alpha = 0.2)

# Checking smaller (591 mL) calories being greater than median(709 mL) calories
temp_star %>%
  filter(serv_size_m_l == 591 &
           calories > median(calories[serv_size_m_l == 709]) & 
           whip == 0) %>%
  View()
```

# Sodium
```{r}
## Sodium 
starbucks %>%
  select(product_name, sodium_mg, size) %>%
  arrange(-sodium_mg) %>%
  View()

# Looking into Chocolate/Chip and its relationship to sodium
starbucks %>%
  filter(!size %in% c("doppio", "solo", "quad", "triple", "1 shot")) %>%   # filtered out low sodium/small sizes
  group_by(chocolate = str_detect(product_name, 'Chip|Choco'), size) %>%   # group by chocolate/chip/mocha
  summarize(m_sodium = mean(sodium_mg)) %>%
  arrange(-m_sodium)

starbucks %>%
  filter(!size %in% c("doppio", "solo", "quad", "triple", "1 shot")) %>%
  group_by(chocolate = str_detect(product_name, 'Chip|Choco'), size) %>%
  ungroup() %>%
  filter(chocolate == FALSE) %>%
  select(product_name, sodium_mg) %>%
  arrange(-sodium_mg)


# Sodium by frappuccino
starbucks %>%
  filter(!size %in% c("doppio", "solo", "quad", "triple", "1 shot")) %>%   # filtered out low sodium/small sizes
  group_by(frappuccino = str_detect(product_name, 'Frappuccino'), size) %>%   # group by frappuccino
  summarize(m_sodium = mean(sodium_mg)) %>%
  arrange(-m_sodium)

# Bar plot of sodium by size and frap-status
starbucks %>%
  filter(!size %in% c("doppio", "solo", "quad", "triple", "1 shot")) %>%   # filtered out low sodium/small sizes
  group_by(frappuccino = str_detect(product_name, 'Frappuccino'), size) %>%   # group by frappuccino
  summarize(m_sodium = mean(sodium_mg)) %>%
  ggplot(aes(fct_relevel(size, c("1 scoop", "trenta", "short", "tall", "grande", "venti")),
             m_sodium, fill = frappuccino)) + 
  geom_col(position = "dodge") + labs(x = "Size", y = "Aerage sodium (mg)")

t.test(starbucks$sodium_mg ~ grepl('Frappuccino', starbucks$product_name))
t.test(starbucks$sodium_mg ~ grepl('Chip|Choco', starbucks$product_name))


```

## Cholesterol 

```{r}
# Cholesterol possible predictors 
summary(lm(cholesterol_mg ~ milk + whip + total_fat_g, starbucks))

# Milk and whip contain fat, thus lm by fat alone
summary(lm(cholesterol_mg ~ total_fat_g, starbucks))

# Box plot of cholesterol by milk, separated by whip
starbucks %>%
  group_by(milk) %>%
  ggplot(aes(milk, cholesterol_mg)) + geom_boxplot() + facet_wrap(~whip) +
  labs(x = "Milk", y = "Cholesterol (mg)")

starbucks %>% 
  group_by(cholesterol_mg) %>%
  summarize(fat = mean(total_fat_g)) %>%
  ggplot(aes(cholesterol_mg, fat)) + geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  labs(y = "Average fat (g)", x = "Cholesterol (mg)")


# Non-cow milk with no whip cream
starbucks %>%
  filter(str_detect(milk, 'none|soy|coconut') & whip == 0) %>%
  summarize(pct = mean(cholesterol_mg <= 5)) # Percent of 5 or less mg of cholesterol drinks

starbucks %>%
  filter(str_detect(milk, 'none') & whip == 0 & cholesterol_mg > 5) %>%
  View()  # Large sizes of "Vanilla Sweet Cream Cold Brew" 


starbucks %>%
  filter(str_detect(milk, 'none|soy|coconut') & whip == 0 & cholesterol_mg > 5) %>%
  View()
```


## Total fat
```{r}

# Total fat by trans/saturated fat
summary(lm(total_fat_g ~ trans_fat_g + saturated_fat_g, starbucks))

# Total fat by milk, whip, size
summary(lm(total_fat_g ~ milk + whip + size, starbucks))

starbucks %>%
  arrange(-total_fat_g, milk, whip) %>%
  View()

```

