---
title: "Heart"
author: "Matthew"
date: "1/6/2022"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(GGally)
theme_set(theme_bw())
heart <- read_csv("C:/Users/Matthew Hondrakis/Downloads/heart.csv")
heart <- heart %>%
  rename_all(tolower) %>%
  mutate(across(where(is.character), as.factor),
         heartdisease = as.factor(heartdisease),
         fastingbs = as.factor(fastingbs),
         chestpaintype = recode(chestpaintype, TA = "Typical Angina", ATA = "Atypical Angina", 
                                NAP = "Non-Anginal Pain", ASY = "Anymptomatic"))
```

# Explore

## Sex
```{r}
heart %>%
  group_by(sex) %>%
  summarize(Percent = mean(heartdisease == 1)) %>%
  ggplot(aes(sex, Percent, fill = sex)) + geom_col()
```

## Max Heart rate
```{r}
heart %>%
  ggplot(aes(heartdisease, maxhr, group = heartdisease)) + geom_boxplot()
```

## Resting ECG
```{r}
heart %>%
  ggplot(aes(restingecg, fill = heartdisease)) + geom_bar(position = "dodge")

```

## Cholesterol 
```{r}
heart %>%
  filter(cholesterol != 0) %>%
  ggplot(aes(heartdisease, cholesterol, color = heartdisease)) + geom_boxplot() + 
  geom_jitter(width = 0.18, alpha = 0.2) + facet_wrap(~sex)

heart %>%
  filter(sex == "M", cholesterol < 10) %>%
  View()

heart %>%
  ggplot(aes(cholesterol)) + geom_histogram()

t.test(heart$cholesterol ~ heart$heartdisease)
```

## Checking Numeric columns
```{r}
heart %>%
  keep(is.numeric) %>%
  gather() %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key, scales = "free")
```

## Oldpeak
```{r}
heart %>%
  count(oldpeak)

heart %>%
  ggplot(aes(oldpeak, color = heartdisease)) + geom_density()
```

## Exercise
```{r}
heart %>%
  ggplot(aes(exerciseangina, fill = heartdisease)) + geom_bar(position = "dodge") + scale_fill_hue(direction = -1)
```


# Model
```{r}
library(tidymodels)
set.seed(123)
heart$heartdisease <- relevel(heart$heartdisease, "1")
heart_split <- initial_split(filter(heart, cholesterol != 0), strata = heartdisease)

heart_train <- training(heart_split)
heart_test <- testing(heart_split)

logmodel <- logistic_reg() %>%
  set_engine("glm")

heart_rec <- recipe(heartdisease ~ ., heart_train) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric())

heart_wkfl <- workflow() %>%
  add_model(logmodel) %>%
  add_recipe(heart_rec)

heart_fit <- heart_wkfl %>%
  last_fit(heart_split)

heart_fit %>% collect_metrics()
heart_fit %>% collect_predictions() %>% roc_curve(heartdisease, .pred_1) %>% autoplot()

fitted_heart <- heart_wkfl %>%
  fit(data = heart_train)

fitted_heart %>% tidy() %>% arrange(-abs(estimate))

```

## Model of Largestest Estimates
```{r}
heart_rec2 <- recipe(heartdisease ~ st_slope + oldpeak + chestpaintype + sex, heart_train) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric())

heart_fit2 <- workflow() %>%
  add_model(logmodel) %>%
  add_recipe(heart_rec2) %>%
  last_fit(heart_split)


```

## Plot both
```{r}
model_res <- heart_fit2 %>%
  unnest(.predictions) %>%
  mutate(model = "Two") %>%
  bind_rows(heart_fit %>%
              unnest(.predictions) %>%
              mutate(model = "One")) %>%
  group_by(model) %>%
  roc_curve(heartdisease, .pred_1)

model_res %>% autoplot() + labs(title = "ROC Curves", subtitle = "Model One: 11 Predictors
Model Two: 4 Predictors")

```

### Metrics
```{r}
heart_fit %>%
  collect_metrics()

heart_fit2 %>%
  collect_metrics()
```



